### ISSUE TITLE
Unable to Package Project.

### ISSUE THREAD

**Issue by bengris32** [frasergeorgeking/UE4_BP_MazeGen_MIT#3]
`UATHelper: Packaging (Windows (64-bit)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): Running: D:\UE\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4_BP_MazeGen_MIT Win64 Development -Project="C:\Users\bengris32\Documents\Unreal Projects\UE4_BP_MazeGen_MIT_v2.0_4.26-experimental\UE4_BP_MazeGen_MIT.uproject"  "C:\Users\bengris32\Documents\Unreal Projects\UE4_BP_MazeGen_MIT_v2.0_4.26-experimental\U
E4_BP_MazeGen_MIT.uproject" -NoUBTMakefiles  -remoteini="C:\Users\bengris32\Documents\Unreal Projects\UE4_BP_MazeGen_MIT_v2.0_4.26-experimental" -skipdeploy -Manifest="C:\Users\bengris32\Documents\Unreal Projects\UE4_BP_MazeGen_MIT_v2.0_4.26-experimental\Intermediate\Build\Manifest.xml" -NoHotReload -log="C:\Users\bengris32\AppData\Roaming\Unreal Engine\Auto
mationTool\Logs\D+UE+UE_4.26\UBT-UE4_BP_MazeGen_MIT-Win64-Development.txt"
UATHelper: Packaging (Windows (64-bit)):   ERROR: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
UATHelper: Packaging (Windows (64-bit)):          (referenced via Target -> UE4_BP_MazeGen_MIT.Build.cs -> ContentBrowser.Build.cs -> AssetTools.Build.cs)
PackagingResults: Error: Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
UATHelper: Packaging (Windows (64-bit)): Took 3.5960388s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\bengris32\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE+UE_4.26\UBT-UE4_BP_MazeGen_MIT-Win64-Development.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error`

Unreal Engine version: 4.26.1

**Comment by frasergeorgeking** [comment]
Thanks for logging this as an issue @bengris32. The packaging issues were related to not properly seperating the editor dependent code from the `UE4_BP_MazeGen_MIT` game module. This should be fixed in the latest master branch update and I'll shortly publish a v2.0.1 release. 

For more specifics on the fix please see [here](https://github.com/frasergeorgeking/UE4_BP_MazeGen_MIT/pull/4).

**Comment by bengris32** [comment]
Nice!
